### ISSUE TITLE
No task for cov-build command

### ISSUE THREAD

**Issue by anukok** [mjdetullio/gradle-coverity-plugin#3]
Hi,

I noticed that you dont have a task for cov-build command which is to be run before the emmit command. Please give me more information about this.

**Comment by mjdetullio** [comment]
`cov-build` is a wrapper for whatever your normal build command is.  It does some magic to listen in on your build and automatically does `cov-emit` and `cov-analyze`.  The point of this plugin is to act as a substitute for `cov-build`, not to support it.

**Comment by anukok** [comment]
If I want to run cov-emit directly, should I give the location of jar files? I tried the cov-emit command by mentioning the location of jar files but it does not find them.

C02RT2U3G8WP:sat-starter-service anushakokkula$ cov-emit-java --classpath build --findsource src --findjars build/libs --dir ~/coverity-build
Coverity Java Emit version 8.1.0 on Darwin 15.4.0 x86_64
Internal version numbers: 5511032c07 p-jasper1-push-24789.298.98

ERROR: Compiler outputs are missing. If this is intentional specify --no-compiler-outputs
C02RT2U3G8WP:sat-starter-service anushakokkula$ ls build/libs/
sat-starter-service-null.jar        sat-starter-service-null.jar.original
C02RT2U3G8WP:sat-starter-service anushakokkula$ 

Can you please suggest.

Thanks,
Anusha

**Comment by mjdetullio** [comment]
This plugin runs `cov-emit` against Gradle projects, you don't run it manually.

I am not offering Coverity support.  Please reach out to Coverity support, stackoverflow, etc.
